CREATE TABLE [dbo].[IPs]
(
    [Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [IP] VARCHAR(45) NOT NULL, 
    [Blocked] BIT NOT NULL, 
    [Notes] VARCHAR(200) NULL
)

GO

CREATE INDEX [IX_IPs_IP] ON [dbo].[IPs] ([IP])
